---
language: node_js
node_js: 8
sudo: false
cache:
  directories:
    - "node_modules"
env:
  global:
    - SCRIVITO_TENANT: "1234567890abcdef1234567890abcdef"
  matrix:
    - TASK: "build"
    - TASK: "eslint"
script: npm run $TASK
